services:
  web:
    image: "nginx:latest"
    restart: "always"
    depends_on:
      - "db"
    environment:
      - "APP_ENV=production"
      - "DEBUG=false"
    command: [nginx -g daemon off;]
    entrypoint: [/docker-entrypoint.sh]
    deploy:
      replicas: 3
  db:
    image: "postgres:15"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=supersecret"
      - "POSTGRES_USER=admin"
    deploy:
      replicas: 1
networks:
  backend-network:
    driver: "bridge"